# Generated by Django 2.2 on 2021-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='carousel/%Y%m%d')),
                ('is_first', models.BooleanField(blank=True)),
            ],
            options={
                'verbose_name': '轮播图片管理',
                'verbose_name_plural': '轮播图片管理',
                'db_table': 'tb_carousel_img',
            },
        ),
    ]
